//Rose A et B


d.ra.vols = ();
d.rb.vols = ();

d.ra.vols.a01 = 0.07;
d.ra.vols.a02 = 0.08;
d.ra.vols.a03 = 0.10;
d.ra.vols.a04 = 0.11;
d.ra.vols.b01 = 0.10;
d.ra.vols.c01 = 0.10;
d.ra.vols.c02 = 0.10;
d.ra.vols.c03 = 0.10;
d.ra.vols.c04 = 0.10;


d.rb.vols.a01 = 0.07;
d.rb.vols.a02 = 0.08;
d.rb.vols.a03 = 0.10;
d.rb.vols.a04 = 0.11;
d.rb.vols.b01 = 0.10;
d.rb.vols.c01 = 0.10;
d.rb.vols.c02 = 0.10;
d.rb.vols.c03 = 0.10;
d.rb.vols.c04 = 0.10;


